update action

diff --git a/.github/workflows/bioconda-packages-check.yml b/.github/workflows/bioconda-packages-check.yml
--- a/.github/workflows/bioconda-packages-check.yml
+++ b/.github/workflows/bioconda-packages-check.yml
@@ -66,19 +66,36 @@ jobs:
 
             set +e
 
-            for CMD in "\$pkg --version" "\$pkg -v" "\$pkg -V"; do
-              if timeout \$TIMEOUT micromamba run -n "\$ENV_NAME" \$CMD >/dev/null 2>&1; then
-                echo "\$pkg: version check success with '\$CMD'" >> logs/results_${{ matrix.chunk }}.txt
+            
+
+            CMD_LIST=("$pkg --version" "$pkg -v" "$pkg -V")
+            SUCCESS=0
+
+            for CMD in "${CMD_LIST[@]}"; do
+              echo "Trying: $CMD"
+              OUTPUT=$(timeout $TIMEOUT micromamba run -n "$ENV_NAME" $CMD 2>&1)
+              STATUS=$?
+
+              if [[ $STATUS -eq 0 && -n "$OUTPUT" ]]; then
+                echo "$pkg: version check success with '$CMD'" >> logs/results_${{ matrix.chunk }}.txt
+                echo "$OUTPUT" >> logs/results_${{ matrix.chunk }}.txt
                 SUCCESS=1
                 break
+              else
+                echo "$pkg: version check failed with '$CMD'" >> logs/errors_${{ matrix.chunk }}.txt
+                echo "$OUTPUT" >> logs/errors_${{ matrix.chunk }}.txt
               fi
             done
 
+            if [[ "$SUCCESS" -eq 0 ]]; then
+              echo "$pkg: all version checks failed"
+            fi
+
+
+
             set -e
 
-            # if [[ "\${SUCCESS:-0}" -eq 0 ]]; then
-            #   echo "\$pkg: version check failed" >> logs/errors_${{ matrix.chunk }}.txt
-            # fi
+            
 
             micromamba remove -y -n "\$ENV_NAME" --all >/dev/null 2>&1
           done < "\$CHUNK_FILE"
